name: Build and Push

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/devops-homeproject:1.0
            ghcr.io/${{ github.repository }}/devops-homeproject:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/devops-homeproject:1.0
          cache-to: type=inline
